[package]
name = "chat-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
rig-core = { version = "0.10.0", features = ["derive"] }
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["full"] }
